services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB:       imigration
      POSTGRES_USER:     imigration
      POSTGRES_PASSWORD: imigration
    ports:
      - 5432:5432
